login/urls.py
from django.conf.urls import url
from login import views

# SET THE NAMESPACE!
app_name = 'login'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'^contractor/$', views.Contractor, name='contractor'),
    url(r'^driver/$', views.Driver, name='driver'),
    url(r'^contractor_login/$', views.contractor_login, name='contractor_login'),
    url(r'^driver_login/$', views.driver_login, name='driver_login'),

]

login/templates/login/C_Details.html
  <div class="container">
    <div class="jumbotron">
<html>
<head>
<meta charset="UTF-8">
<title>Drivers</title>
</head>
<body>

<h1>{{ cutomer.id }}</h1>
<h2>{{ driver.D_Name }}</h2>


<!--<p>Username: {{ customer.C_Username }}</p>-->

<!--<p>Password: {{ customer.C_Password }}</p>-->

<p>Name: {{ customer.C_Name }}</p>

<p>Address: {{ customer.C_Address }}</p>

<p>Phone no: {{ customer.C_Ph_no }}</p>

<p>Driver-id: {{ customer.C_D_id }}</p>

<p>Dustbin-id: {{ customer.C_Dustbin_ID }}</p>


<br>
<p>Go back to the <a href="/customer"> List of Clients </a></p>
<br>
<p> Delete the Clients's Record <a href="/customer/{{driver.id}}/"> Remove </a></p>


</body>
</html>
    </div>
  </div>

login/templates/login/D_Details.html
<html>
<head>
<meta charset="UTF-8">
<title>Drivers</title>
</head>
<body>

<h1>{{ driver.id }}</h1>
<h2>{{ driver.D_Name }}</h2>


<!--<p>Username: {{ driver.D_Username }}</p>-->

<!--<p>Password: {{ driver.D_Password }}</p>-->

<p>Address: {{ driver.D_Address }}</p>

<p>Phone no: {{ driver.D_Ph_no }}</p>

<p>Truck No: {{ driver.Truck_no }}</p>
<br>
<p>Go back to the <a href="/driver1"> List of Drivers </a></p>
<br>
<p> Delete the Driver's Record <a href="/driver1/{{driver.id}}/"> Remove </a></p>


</body>
</html>

login/templates/login/Map.html
{% extends 'login/page.html' %}
{% block body_block %}
  <div class="container-fluid">
    <!--<div class="jumbotron">-->

	<title>design</title

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
*{
	box-sizing: border-box;
}

.container-fluid{
  background: url("/static/images/68.jpg") 50% 0 no-repeat fixed;
     color: black;
     <!--width:100%;-->
     height: 700px;
     padding:50px;
}
.jumbotron {
  position:relative;
  overflow:hidden;
  background:cover;
}

.jumbotron .container {
  position:relative;
  z-index:2;
  background:rgba(0,0,0,0.2);
  padding:2rem;
  border:1px solid rgba(0,0,0,0.1);
  border-radius:3px;
   background:#66CC66;
}
.jumbotron-background {
  object-fit:cover;
  font-family: 'object-fit: cover;';
  position:absolute;
  top:0;
  margin-left:-4.5vw;
  z-index:1;
  width:100%;
  height:100%;
  opacity:0.5;
   background:#DCF1DA;

}

.success {
  border-color: #4CAF50;
  color: green;
  width:15vw;
}

.success:hover {
  background-color: #4CAF50;
  color: white;
}


img.blur {
	-webkit-filter: blur(4px);
	filter: blur(4px);
  filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius='4');

}

.footer {
margin-top:20px;
}

hr{
clear:both;
}

@media screen and (max-width: 600px){
	body{
		background: grey;
	}
} 

</head>
</style>

<div>
	<div class="jumbotron jumbotron-fluid bg-dark">
		<div class="jumbotron-background"><img src="static/images/garbage.png" class="blur "></div>
		<div class="container">
		<h1><center><b> Welcome Contractor {{ User.user}} </b></center></h1><br>
		<h4><p>Now u can add,remove drivers, clients and bins. Hope you are doing well.<br>
			Responsible management of waste is an essential aspect of sustainable building.
			In this context, managing waste means eliminating waste where possible; minimizing waste where feasible; and reusing materials which might otherwise become waste.
			Solid waste management practices have identified the reduction, recycling, and reuse of wastes as essential for sustainable management of resources.
		</p> </h4>
		</div>
<!--<button	type="button">Click Here</button >-->
	</div>

<div>
	<div class="row thm">
	<div class="client col-sm-3 text-center">
		<form method="GET" action="{% url 'Driver' %}">
	<button class="btn success">Register Drivers</button>
</form>
</div>

<div class="driver col-sm-3 text-center">
	<form method="GET" action="{% url 'Customer' %}">
    <button class="btn success">Register Customers</button>
</form>

</div>

<div class="bins col-sm-3 text-center">
<form method="GET" action="{% url 'Trashcan' %}">
    <button class="btn success">Register Bins</button>
</form>
</div>

<div class="see_all col-sm-3 text-center">
	<form method="GET" action="{% url 'Map' %}">
		<button class="btn success">See All</button>
	</form>
</div>
	</div>
<div class="footer">
<hr>
<p>&copy 2019 Zapbuild Technologies Pvt. Ltd. All Rights Reserved</p>
</div>
</div>
</div>
  </div>
		{% endblock %}

login/templates/login/T_Details.html
<html>
<head>
<meta charset="UTF-8">
<title> Trash Cans </title>
</head>
<body>

<h1>{{ trash.id }}</h1>

<p>Customer Name: {{ customer.C_Name }}</p>

<p>Driver Name: {{ driver.D_Name }}</p>

<p>Coordinates {{ trash.T_x_c }}</p>

<br>
<p>Go back to the <a href="/trash"> List of Trashcans </a></p>
<br>
<p> Delete the Clients's Record <a href="/trash/{{driver.id}}/"> Remove </a></p>

</body>
</html>

login/templates/login/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Green City</title>
   
 <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-brand" href="{% url 'index' %}">CleanCity</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'login:contractor' %}">Register</a></li>


          <!--{# Some logic on what to display for last item#}-->
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="dropdown drop-menu">
                <a href="#" class="dropdown-toggle nav-item" data-toggle="dropdown">Login <i class="fa fa-angle-down"></i></a>
                <ul class="dropdown-menu login-drop">
                  <li><a href="{% url 'login:contractor_login' %}" class="nav-item" title="contractor">Contractor<i class="fa fa-home"></i></a></li>
                  <li><a href="{% url 'login:driver_login' %}" class="nav-item" title="driver">Driver<i class="fa fa-truck"></i></a></li>
                  <!--<li><a href="#" class="nav-item" title="contractor">Contractor<i class="fa fa-user-secret"></i></a></li>-->
                </ul>
            </li>
          {% endif %}

</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </body>
</html>

login/templates/login/index.html
{% extends "login/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

login/templates/login/list1.html
<html>
<head>
<meta charset="UTF-8">
<title> Clients </title>
</head>
<body>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>List of all registered Clients </h1>

{% for customer in allcustomers %}

<a href="{{customer.id}}"><span>{{customer.id}}. </span>{{customer.C_Name}}</a>

<br><br>
{% endfor %}
</table>

</body>
</html>

login/templates/login/list2.html
<html lang="en">
<head>
<meta charset="UTF-8">
<title> Drivers </title>
</head>
<body>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>List of Drivers </h1>

{% for driver in alldrivers %}

<a href="{{driver.id}}"><span> {{driver.id}}.</span> {{ driver.Name }} - {{driver.Username}} </a>

<br><br>
{% endfor %}
</table>

</body>
</html>

login/templates/login/list3.html
<html>
<head>
<meta charset="UTF-8">
<title> Trash Cans </title>
</head>
<body>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>List of all registered Trashcans </h1>

{% for t in alltrash %}

<a href="{{ t.id }}"><span> {{ t.id}}.</span> {{t.T_ID}} </a>

<br><br>
{% endfor %}
</table>

</body>
</html>

login/templates/login/log.html
{% extends 'login/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>

<form method="post" action="{% url 'login:contractor_login' %}">
          {% csrf_token %}

          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">

    <button type="submit" name="" value="Login">Login</button>

</form>


 </div>
  </div>
{% endblock %}

login/templates/login/log1.html
{% extends 'login/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Driver Login here  :</h1>

<form method="post" action="{% url 'login:driver_login' %}">
          {% csrf_token %}
          <!--{# A more "HTML" way of creating the login form#}-->
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">

    <button type="submit" name="" value="Login">Login</button>

</form>


 </div>
  </div>
{% endblock %}

login/templates/login/registration.html
{% extends "login/base.html" %}
{% load staticfiles %}

{% block body_block %}

 <style>
		.form{
	max-width: 500px;
	padding: 10px 20px;
	background: #f4f7f8;
	margin: 10px auto;
	padding: 20px;
	background: #f4f7f8;
	border-radius: 8px;
	font-family: Georgia, "Times New Roman", Times, serif;
}
.form legend {
	font-size: 2.4em;
	margin-bottom: 2px;
}

.form button
{
	position: relative;
	display: block;
	padding: 19px 39px 18px 39px;
	color: #FFF;
	margin: 0 auto;
	background: #1abc9c;
	font-size: 18px;
	text-align: center;
	font-style: normal;
	width: 100%;
	border: 1px solid #16a085;
	border-width: 1px 1px 3px;
	margin-bottom: 10px;
}
.form input[type="submit"]:hover,
.form input[type="button"]:hover
{
	background: #109177;
}
.form input[type="text"],.form select
{

    font-family: Georgia, "Times New Roman", Times, serif;
	background: rgba(255,255,255,.1);
	border: none;
	border-radius: 4px;
	font-size: 15px;
	margin: 0;
	outline: 0;
	padding: 10px;
	width: 100%;
	box-sizing: border-box;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	background-color: #e8eeef;
	color:#8a97a0;
	-webkit-box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
	box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
	margin-bottom: 30px;

}
<!--.myfieldclass-->
<!--{-->
	<!--max-width: 500px;-->
	<!--padding: 10px 20px;-->
	<!--background: #f4f7f8;-->
	<!--margin: 10px auto;-->
	<!--padding: 20px;-->
	<!--background: #f4f7f8;-->
	<!--border-radius: 8px;-->
	<!--font-family: Georgia, "Times New Roman", Times, serif;-->
<!--}
</style>

  <div class="container">
    <div class="jumbotron">

      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}



<form enctype="multipart/form-data" method="POST" class="form">
     <legend><center>Register Here</center></legend>
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          {{ driver_form.as_p }}
          <button type="submit" name="" value="Register">Register</button>
</form>

      {% endif %}
        <!--</center>-->
    </div>
  </div>
{% endblock %}

login/templates/login/showd.html
<!DOCTYPE html>
<html>
  <head>
<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  	<meta charset="utf-8">
<style>
html {
	height: 100%;
}
body {
	height: 100%;
	margin: 0;
	padding: 0;
}
#map-canvas {
	height: 80%;
}
#iw_container .iw_title {
	font-size: 16px;
	font-weight: bold;
}
.iw_content {
	padding: 15px 15px 15px 0;
}

</style>
</head>
  <body>
<!--<div class="jumbotron">-->
      <div id="map-canvas" class="jumbotron">
  </div>


  <div class="container-fluid">

 	{% for trash in data %}
	<h3>Trash Can ID :{{ trash.id }}</h3>
    <div class="row thm">

      <div class="col-sm-5 text-center"><div class="thumbnail"><a href="#"><iframe width="430" height="280" frameborder="0" src="https://app.ubidots.com/ubi/getchart/Xdu9xxivRQoipfJiwI4dm_LfREs"></iframe><div class="caption"><strong> Trash percent </strong></div></a></div></div>
      <div class="col-sm-5 text-center"><div class="thumbnail"><a href="#"><iframe width="430" height="280" frameborder="0" src="https://app.ubidots.com/ubi/getchart/l_HpNeX9_cd98iWGGAPI1FA9q3M"></iframe><div class="caption"><strong> Last day record </strong></div></a></div></div>

    </div>
	{% endfor %}
  </div>

  <!--<div class="col-sm-4"><iframe src="{% url 'customer' %}"></iframe> </div>-->
  <!--<div class="col-sm-4"><iframe src="{% url 'driver1' %}"></iframe></div>-->
  <!--<div class="col-sm-4"><iframe src="{% url 'trash' %}"></iframe></div>-->

  <!--<div class="container-fluid">-->

 	<!--{% for trash in markersData1 %}-->
	<!--<h3>Trash Can ID :{{ trash.id }}</h3>-->
    <!--<div class="row thm">-->
      <!--<div class="col-sm-6 text-center" id="{{ trash.id }}x"> {{ trash.T_x_c }} </div>-->
      <!--<div class="col-sm-6 text-center" id="{{ trash.id }}y"> {{ trash.T_y_c }}</div>-->
    <!--</div>-->

	<!--{% endfor %}-->
  <!--</div>-->
<div class ="footer text-center"> Green City 2019 , All rights Reserved </div>

  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT79IjIXNg69ChpliTTd3m6_qnTjM8WAQ"></script>

<script>
var map;
var infoWindow;
var markersData1 = " {{ markersData1 }} ";
//JSON.parse('{ "name":"John", "age":30, "city":"New York"}');
// markersData variable stores the information necessary to each marker
var markersData = [
   {
      lat: 30.7097739,
      lng: 76.6858297,
      name: "Trash 01",

   },
   {
      lat: 30.7132329,
      lng: 76.6279277,
      name: "Trash 02",
   },
   {
      lat: 30.755587,
      lng: 76.7999578,
      name: "Trash 03",
   }
];

function initialize() {
   var mapOptions = {
      center: new google.maps.LatLng(30.7097739,76.6858297),
      zoom: 12,
      mapTypeId: 'roadmap',
   };

   map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

   // a new Info Window is created
   infoWindow = new google.maps.InfoWindow();

   // Event that closes the Info Window with a click on the map
   google.maps.event.addListener(map, 'click', function() {
      infoWindow.close();
   });

   // Finally displayMarkers() function is called to begin the markers creation
   displayMarkers();
}
google.maps.event.addDomListener(window, 'load', initialize);


// This function will iterate over markersData array
// creating markers with createMarker function
function displayMarkers(){

   // this variable sets the map bounds according to markers position
   var bounds = new google.maps.LatLngBounds();

   // for loop traverses markersData array calling createMarker function for each marker
   for (var i = 0; i < markersData.length; i++){

      var latlng = new google.maps.LatLng(markersData[i].lat,markersData[i].lng );
      var name = markersData[i].name;
      createMarker(latlng, name);

      // marker position is added to bounds variable
      bounds.extend(latlng);
   }

   // Finally the bounds variable is used to set the map bounds
   // with fitBounds() function
   map.fitBounds(bounds);
}

// This function creates each marker and it sets their Info Window content
function createMarker(latlng, name, address1, address2, postalCode){
   var marker = new google.maps.Marker({
      map: map,
      position: latlng,
      title: name
   });

   // This event expects a click on a marker
   // When this event is fired the Info Window content is created
   // and the Info Window is opened.
   google.maps.event.addListener(marker, 'click', function() {

      // Creating the content to be inserted in the infowindow
      var iwContent = '<div id="iw_container">' +
            '<div class="iw_title">' + name + '</div>' +
         '<div class="iw_content">' + address1 + '<br />' +
         address2 + '<br />' +
         postalCode + '</div></div>';

      // including content to the Info Window.
      infoWindow.setContent(iwContent);

      // opening the Info Window in the current map and at the current marker location.
      infoWindow.open(map, marker);
   });
}

</script>
</html>

login/templates/login/signup.html
{% extends 'login/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">

<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}


input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}


button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}


.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}


.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}


.container {
  padding: 16px;
}


.clearfix::after {
  content: "";
  clear: both;
  display: table;
}


@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<div>

<form action="/action_page.php" style="border:1px solid #ccc">
  <div class="container">
    <h1>Register Bin</h1>
    <p>Please fill it carefully.</p>
    <hr>

    <label for="binid"><b>Bin_Id</b></label>
    <input type="text" placeholder="Enter bin_id" name="binid" required>

    <label for="Client"><b>Client Name</b></label>
    <input type="text" placeholder="Enter Client Name" name="client" required>

    <label for="driver"><b>Driver Name</b></label>
    <input type="text" placeholder="Enter Driver Name" name="driver" required>

    <label for="location"><b>Client Address</b></label>
    <input type="text" placeholder="Enter Client's Address" name="location" required>



    <div class="clearfix">
      <button type="button" class="cancelbtn">Cancel</button>
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>
</div>
    </div>
    {% endblock %}